# Generated by Django 4.0.3 on 2022-03-31 07:10

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 31, 7, 10, 6, 571293)),
        ),
    ]
