# Generated by Django 4.0.3 on 2022-03-31 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content_alter_post_publish_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 31, 10, 52, 42, 40727)),
        ),
    ]
