# Generated by Django 4.0.3 on 2022-04-02 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_publish_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 2, 19, 57, 54, 885054)),
        ),
    ]
