# Generated by Django 4.0.3 on 2022-04-04 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_publish_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 4, 7, 7, 48, 294841)),
        ),
    ]
