# Generated by Django 4.0.3 on 2022-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
