# Generated by Django 4.0.3 on 2022-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
