# Generated by Django 4.0.3 on 2022-04-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0004_category_slug_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
