# Generated by Django 4.0.3 on 2022-04-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0005_rename_description_category_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
